(() => {
'use strict';
const DATA=window.NEO_DATA, PLANNER=window.NEO_PLANNER, root=document.getElementById('app');
const KEY='neoTrainerV421';
const defaults={route:'home',selectedExercise:null,calendarCursor:null,selectedSession:null,profile:{name:'',sex:'male',age:null,weight:null,height:null,activity:'',goal:'',minutesPerSession:30,weekdays:[1,3,5],equipment:['none'],limitations:['none']},stats:{xp:0,workouts:0,streak:0,bestStreak:0,totalMinutes:0},plan:null};
function clone(x){return JSON.parse(JSON.stringify(x))}
function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x&&typeof x==='object'?x:null}catch{return null}}
const old=read(),state={...clone(defaults),...(old||{})};state.profile={...defaults.profile,...(old?.profile||{})};state.stats={...defaults.stats,...(old?.stats||{})};
['xp','workouts','streak','bestStreak','totalMinutes'].forEach(k=>state.stats[k]=Math.max(0,Number(state.stats[k])||0));
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function exById(id){return DATA.exercises.find(x=>x.id===id)}
function asset(path){return window.NEO_ASSETS?.[path]||path}
function imageKey(ex,phase='main'){const sex=state.profile.sex==='female'?'female':'male';const id=ex?.id||'mobility-flow';const suffix=phase==='start'||phase==='end'?`-${phase}`:'';return `${sex}/${id}${suffix}`}
function imageFile(ex,phase='main'){const key=imageKey(ex,phase);const mapped=window.NEO_IMAGES?.[key];return asset(mapped||`assets/exercises/${key}.svg`)}
function avatar(){const sex=state.profile.sex==='female'?'female':'male';return asset(window.NEO_IMAGES?.[`${sex}/avatar`]||`assets/exercises/${sex}/avatar.svg`)}
function bmi(){return PLANNER.bmi(state.profile)}
function currentPlan(){return state.plan?.ready?state.plan:PLANNER.makePlan(state.profile,state.stats)}
function level(){const x=state.stats.xp;return x>=5000?'Elite':x>=2500?'Avanzado':x>=1000?'Intermedio':x>=250?'Principiante':'Inicial'}
const nav=[['home','⌂','Inicio'],['calendar','▣','Calendario'],['workouts','✦','Entrenamientos'],['exercises','⚕','Ejercicios'],['progress','▥','Progreso'],['seven','◴','7 Min Workout'],['profile','●','Perfil']];
function go(route){state.route=route;save();render();scrollTo(0,0)}
function navHtml(cls='nav'){return `<nav class="${cls}">${nav.map(([r,i,l])=>`<button data-route="${r}" class="${state.route===r?'active':''}"><span>${i}</span>${l}</button>`).join('')}</nav>`}
function shell(content){return `<aside class="sidebar"><div class="brand"><b>NEO</b><span>TRAINER</span></div><section class="profile-card"><img src="${avatar()}" alt="Perfil"><h3>¡Hola, ${esc(state.profile.name||'Usuario')}!</h3><p>${level()}</p><strong>★ ${state.stats.xp} XP</strong><div><span>🔥 ${state.stats.streak} días</span><span>${state.stats.workouts} entrenos</span></div></section>${navHtml()}<footer>v${DATA.version} · ${DATA.build}<br>Creada por <a href="https://nachuss.github.io/" target="_blank" rel="noopener">@NachusS ↗</a></footer></aside><main class="main">${content}</main><div id="overlay" class="overlay" hidden></div><aside id="drawer" class="drawer" aria-hidden="true"><header><b>NEO Trainer</b><button id="closeMenu">✕</button></header><div class="drawer-user"><img src="${avatar()}" alt="Perfil"><div><b>${esc(state.profile.name||'Usuario')}</b><small>${level()} · ${state.stats.xp} XP</small></div></div>${navHtml('drawer-nav')}<footer>Creada por <a href="https://nachuss.github.io/" target="_blank" rel="noopener">@NachusS ↗</a></footer></aside><nav class="bottom-nav">${[['home','⌂','Inicio'],['workouts','✦','Entrenos'],['exercises','⚕','Ejercicios'],['seven','◴','7 Min'],['profile','●','Perfil']].map(([r,i,l])=>`<button data-route="${r}" class="${state.route===r?'active':''}"><span>${i}</span><small>${l}</small></button>`).join('')}</nav><div id="modalRoot"></div>`}
function topbar(title){return `<header class="topbar"><button id="openMenu">☰</button><h1>${title}</h1><button data-route="profile" class="avatar-btn"><img src="${avatar()}" alt="Perfil"></button></header>`}
function metric(label,value,sub=''){return `<div class="panel metric"><small>${label}</small><b>${value}</b><span>${sub}</span></div>`}
function youtubeUrl(q){return `https://www.youtube.com/results?search_query=${encodeURIComponent(q)}`}
function profileReady(){return PLANNER.readiness(state.profile)}
function home(){const b=bmi(),bi=PLANNER.bmiLabel(b),p=currentPlan();return shell(`${topbar('Inicio')}<section class="metrics">${metric('XP total',state.stats.xp,'Puntos reales')}${metric('Entrenamientos',state.stats.workouts,'Completados')}${metric('Racha actual',`${state.stats.streak} días`,'Uso consecutivo')}${metric('IMC',b?b.toFixed(1):'—',bi.label)}</section><div class="home-grid"><section class="panel profile-summary"><img src="${avatar()}" alt="Perfil"><div><h2>${esc(state.profile.name||'Completa tu perfil')}</h2><dl><div><dt>Sexo</dt><dd>${state.profile.sex==='female'?'Mujer':'Hombre'}</dd></div><div><dt>Edad</dt><dd>${state.profile.age?`${state.profile.age} años`:'—'}</dd></div><div><dt>Peso</dt><dd>${state.profile.weight?`${state.profile.weight} kg`:'—'}</dd></div><div><dt>Altura</dt><dd>${state.profile.height?`${state.profile.height} cm`:'—'}</dd></div><div><dt>IMC</dt><dd>${b?`${b.toFixed(1)} · ${bi.label}`:'—'}</dd></div></dl><button class="btn primary" data-route="profile">Ver / editar perfil</button></div></section><section class="panel recommendation"><div><span class="tag">PLAN PERSONALIZADO</span><h2>${p.ready?'Tu entrenamiento recomendado':'Falta completar el perfil'}</h2><p>${p.reason}</p>${p.ready?`<ul><li>${p.days} días por semana</li><li>Intensidad ${p.intensity.label.toLowerCase()}</li><li>${p.intensity.sets} series · ${p.intensity.rest}s de descanso</li><li>${p.exercises.length} ejercicios disponibles</li></ul>`:''}<button class="btn primary" id="generatePlan">${p.ready?'Generar mi calendario':'Completar perfil'}</button></div><img src="${imageFile(p.exercises?.[0]||DATA.exercises[0])}" alt="Ejercicio recomendado"></section></div><section class="panel quick-actions"><button data-route="calendar">Abrir calendario</button><button data-route="workouts">Ver entrenamientos</button><button data-route="seven">Iniciar 7 Min Workout</button></section>`)}
function exerciseCards(list){return `<section class="exercise-grid">${list.map(x=>`<article class="exercise-card panel" data-exercise="${x.id}"><img src="${imageFile(x)}" alt="${esc(x.name)}"><div><small>${x.area}</small><h3>${x.name}</h3><span>Nivel ${x.level} · ${x.reps}</span></div></article>`).join('')}</section>`}
function exercises(){return shell(`${topbar('Ejercicios')}<section class="panel intro"><h2>Biblioteca de cuerpo completo</h2><p>${DATA.exercises.length} ejercicios para pecho, espalda, brazos, piernas, glúteos, core, movilidad y cardio. La selección del plan se adapta al perfil, material y limitaciones.</p></section>${exerciseCards(DATA.exercises)}`)}
function detail(id){const ex=exById(id)||DATA.exercises[0],b=bmi();return shell(`${topbar(ex.name)}<div class="detail-layout"><div><section class="panel hero-poses"><div><h3>POSICIÓN INICIAL</h3><img src="${imageFile(ex,'start')}" alt="Posición inicial de ${esc(ex.name)}"></div><div><h3>REFERENCIA DEL EJERCICIO</h3><img src="${imageFile(ex,'end')}" alt="Realización de ${esc(ex.name)}"></div></section><div class="info-grid"><section class="panel"><h3>EXPLICACIÓN PASO A PASO</h3><ol>${ex.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><a class="btn youtube" href="${youtubeUrl(ex.youtube)}" target="_blank" rel="noopener">▶ Ver ejemplos en YouTube</a></section><section class="panel"><h3>MÚSCULOS PRINCIPALES</h3><img class="anatomy" src="${asset('assets/exercises/anatomy.jpg')}" alt="Músculos"><p>${esc(ex.muscles)}</p></section><section class="panel stats"><div><small>Nivel</small><b>${ex.level}</b></div><div><small>Repeticiones</small><b>${ex.reps}</b></div><div><small>Impacto</small><b>${ex.impact}</b></div><div><small>Material</small><b>${ex.equipment.join(', ')}</b></div></section></div></div><aside><section class="panel"><h3>ADAPTACIÓN DEL PERFIL</h3><p>${profileReady()?`Valorado para ${state.profile.age} años, IMC ${b.toFixed(1)}, actividad ${state.profile.activity} y tus limitaciones.`:'Completa tu perfil para recibir una valoración personalizada.'}</p></section><section class="panel"><h3>CONSEJOS</h3><ul><li>Detén la serie si pierdes la técnica.</li><li>Respira con normalidad.</li><li>No entrenes con dolor agudo.</li></ul></section></aside></div>`)}
function workouts(){const p=currentPlan();return shell(`${topbar('Entrenamientos')}${!p.ready?`<section class="panel empty"><h2>Completa tu perfil</h2><p>${p.reason}</p><button class="btn primary" data-route="profile">Ir al perfil</button></section>`:`<section class="panel plan-card"><div><span class="tag">PLAN DE 4 SEMANAS</span><h2>${p.days} días por semana · ${p.intensity.label}</h2><p>${p.reason}</p></div><div class="plan-stats"><b>${p.sessions.length}<small>sesiones</small></b><b>${state.profile.minutesPerSession}<small>min/sesión</small></b><b>${p.intensity.sets}<small>series</small></b></div><button id="generatePlan" class="btn primary">Regenerar calendario</button></section><section class="session-list">${p.sessions.slice(0,8).map(s=>sessionCard(s)).join('')}</section>`}`)}
function sessionCard(s){return `<article class="panel session-card" data-session="${s.id}"><div><small>${new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'short'}).format(new Date(s.date+'T12:00:00'))}</small><h3>${s.title}</h3><span>${s.exercises.length} ejercicios · ${s.minutes} min</span></div><b>${s.completed?'✓':'›'}</b></article>`}
function monthKey(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`}
function calendar(){const p=state.plan?.ready?state.plan:currentPlan();let cursor=state.calendarCursor?new Date(state.calendarCursor+'-01T12:00:00'):new Date();if(p.ready&&!state.calendarCursor&&p.sessions.length)cursor=new Date(p.sessions[0].date+'T12:00:00');const y=cursor.getFullYear(),m=cursor.getMonth(),first=(new Date(y,m,1).getDay()+6)%7,total=new Date(y,m+1,0).getDate(),sessions=new Map((p.sessions||[]).map(s=>[s.date,s]));let cells='';for(let i=0;i<first;i++)cells+='<div class="calendar-empty"></div>';for(let d=1;d<=total;d++){const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,s=sessions.get(iso);cells+=`<button class="calendar-day ${s?'scheduled':''} ${s?.completed?'done':''}" ${s?`data-session="${s.id}"`:''}><b>${d}</b>${s?`<small>${s.completed?'Completado':s.title}</small>`:''}</button>`}return shell(`${topbar('Calendario')}<section class="panel calendar-panel"><div class="calendar-toolbar"><button id="prevMonth">‹</button><div><h2>${new Intl.DateTimeFormat('es-ES',{month:'long',year:'numeric'}).format(cursor)}</h2><p>${p.ready?'Pulsa en un día programado para ver sus ejercicios.':'Completa tu perfil para programar sesiones.'}</p></div><button id="nextMonth">›</button></div><div class="week">${['L','M','X','J','V','S','D'].map(x=>`<b>${x}</b>`).join('')}</div><div class="calendar">${cells}</div><div class="calendar-actions"><button id="generatePlan" class="btn primary">Generar / actualizar plan</button></div></section>`)}
function sessionModal(id){const p=state.plan?.ready?state.plan:currentPlan(),s=p.sessions.find(x=>x.id===id);if(!s)return '';return `<div class="modal-backdrop" id="sessionModal"><section class="modal-card"><header><div><small>${new Intl.DateTimeFormat('es-ES',{dateStyle:'full'}).format(new Date(s.date+'T12:00:00'))}</small><h2>${s.title}</h2><p>${s.minutes} min · ${s.sets} series · ${s.rest}s descanso</p></div><button id="closeModal">✕</button></header><div class="modal-exercises">${s.exercises.map((id,i)=>{const ex=exById(id);return `<button data-exercise="${id}"><img src="${imageFile(ex)}" alt="${esc(ex.name)}"><span><b>${i+1}. ${ex.name}</b><small>${ex.reps} · ${ex.muscles}</small></span><em>Ver ficha ›</em></button>`}).join('')}</div><footer><button class="btn success" id="completeSession" data-id="${s.id}" ${s.completed?'disabled':''}>${s.completed?'Sesión completada':'Marcar como completada'}</button></footer></section></div>`}
function progress(){const pct=Math.min(100,Math.round(state.stats.workouts/20*100));return shell(`${topbar('Progreso')}<section class="metrics">${metric('Entrenamientos',state.stats.workouts)}${metric('XP',state.stats.xp)}${metric('Mejor racha',`${state.stats.bestStreak} días`)}${metric('Tiempo total',`${state.stats.totalMinutes} min`)}</section><section class="panel progress-panel"><h2>Progreso real</h2><p>Todos los valores parten de cero y solo aumentan al completar sesiones.</p><div class="progress"><span style="width:${pct}%"></span></div></section>`)}
let timer=null,remaining=420;
function seven(){const risk=PLANNER.riskScore(state.profile),sequence=DATA.seven.map((x,i)=>({...x,ex:exById(x.exercise),minute:i+1})),idx=Math.min(sequence.length-1,Math.floor((420-remaining)/60)),active=sequence[idx];return shell(`${topbar('7 Minute Workout')}<section class="panel seven"><div><span class="tag">7 MINUTOS GUIADOS</span><h2>${risk>=4?'Versión adaptada de bajo impacto':'Rutina de cuerpo completo'}</h2><div id="timer">${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}</div><h3 id="activeExercise">Minuto ${active.minute}: ${active.ex.name}</h3><p id="activeSteps">${active.ex.steps.join(' ')}</p><div class="timer-actions"><button id="timerBtn" class="btn primary" ${profileReady()?'':'disabled'}>${timer?'Pausar':remaining<420?'Reanudar':'Iniciar'}</button><button id="resetTimer" class="btn">Reiniciar</button><a class="btn youtube" href="${youtubeUrl(active.ex.youtube)}" target="_blank" rel="noopener">▶ Vídeo del ejercicio</a></div></div><img id="activeImage" src="${imageFile(active.ex)}" alt="${esc(active.ex.name)}"></section><section class="panel minute-plan"><h2>Plan minuto a minuto</h2>${sequence.map(x=>`<article class="${x.minute===active.minute?'active':''}"><b>${x.minute}</b><img src="${imageFile(x.ex)}" alt="${esc(x.ex.name)}"><div><h3>${x.ex.name}</h3><p>${x.ex.steps[0]}</p></div><a href="${youtubeUrl(x.ex.youtube)}" target="_blank" rel="noopener">YouTube</a></article>`).join('')}</section><section class="panel video-list"><h2>Vídeos completos de 7 Minute Workout</h2>${DATA.sevenVideos.map(v=>`<a href="${youtubeUrl(v.query)}" target="_blank" rel="noopener">▶ ${v.name}</a>`).join('')}</section>`)}
function profile(){const b=bmi(),bi=PLANNER.bmiLabel(b);return shell(`${topbar('Perfil')}<div class="profile-layout"><section class="panel"><h2>Datos personales y planificación</h2><div class="form-grid"><label>Nombre<input id="name" value="${esc(state.profile.name)}"></label><label>Sexo<select id="sex"><option value="male" ${state.profile.sex==='male'?'selected':''}>Hombre</option><option value="female" ${state.profile.sex==='female'?'selected':''}>Mujer</option></select></label><label>Edad<input id="age" type="number" min="16" max="90" value="${state.profile.age??''}"></label><label>Peso (kg)<input id="weight" type="number" min="35" max="250" step="0.1" value="${state.profile.weight??''}"></label><label>Altura (cm)<input id="height" type="number" min="130" max="220" value="${state.profile.height??''}"></label><label>Actividad<select id="activity"><option value="">Selecciona</option>${DATA.activity.map(([v,l])=>`<option value="${v}" ${state.profile.activity===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Objetivo<select id="goal"><option value="">Selecciona</option>${DATA.goals.map(([v,l])=>`<option value="${v}" ${state.profile.goal===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Minutos por sesión<input id="minutes" type="number" min="7" max="90" value="${state.profile.minutesPerSession}"></label></div><h3>Días de entrenamiento</h3><div class="weekday-checks">${DATA.weekdays.map(([v,l])=>`<label><input type="checkbox" name="weekdays" value="${v}" ${state.profile.weekdays.map(Number).includes(Number(v))?'checked':''}><span>${l.slice(0,3)}</span></label>`).join('')}</div><h3>Material disponible</h3><div class="checks">${DATA.equipment.map(([v,l])=>`<label><input type="checkbox" name="equipment" value="${v}" ${state.profile.equipment.includes(v)?'checked':''}>${l}</label>`).join('')}</div><h3>Limitaciones</h3><div class="checks">${DATA.limitations.map(([v,l])=>`<label><input type="checkbox" name="limitations" value="${v}" ${state.profile.limitations.includes(v)?'checked':''}>${l}</label>`).join('')}</div><div class="actions"><button id="saveProfile" class="btn primary">Guardar y recalcular plan</button><button id="resetAll" class="btn">Reiniciar aplicación</button></div><p class="note">La planificación y el IMC son orientativos. Consulta con un profesional sanitario ante enfermedad, embarazo, lesión importante o síntomas durante el ejercicio.</p></section><aside class="panel bmi-card"><img src="${avatar()}" alt="Perfil"><small>Índice de masa corporal</small><b>${b?b.toFixed(1):'—'}</b><span class="status ${bi.tone}">${bi.label}</span><p>Se combina con edad, sexo, actividad, objetivos, disponibilidad, material, limitaciones y progreso.</p></aside></div>`)}
function render(){try{const views={home,calendar,workouts,exercises,progress,seven,profile};const html=state.route==='detail'?detail(state.selectedExercise):(views[state.route]||home)();root.innerHTML=html;if(state.selectedSession)document.getElementById('modalRoot').innerHTML=sessionModal(state.selectedSession);bind();bindImageFallbacks()}catch(e){console.error(e);root.innerHTML=`<div class="fatal-screen"><div><h1>Error al cargar</h1><pre>${esc(e.message)}</pre><button id="resetAll">Restablecer</button></div></div>`;document.getElementById('resetAll')?.addEventListener('click',()=>{localStorage.removeItem(KEY);location.reload()})}}
function bindImageFallbacks(){
  const extensions=['webp','jpg','jpeg','png','svg'];
  document.querySelectorAll('img').forEach(img=>{
    img.addEventListener('error',()=>{
      const raw=img.getAttribute('src')||'';
      const clean=raw.split('?')[0];
      const match=clean.match(/^(.*)\.([a-zA-Z0-9]+)$/);
      if(match){
        const current=match[2].toLowerCase();
        const idx=extensions.indexOf(current);
        if(idx>=0 && idx<extensions.length-1){
          img.src=`${match[1]}.${extensions[idx+1]}`;
          return;
        }
      }
      if(img.dataset.finalFallback)return;
      img.dataset.finalFallback='1';
      const sex=state.profile.sex==='female'?'female':'male';
      img.src=asset(window.NEO_IMAGES?.[`${sex}/mobility-flow`]||`assets/exercises/${sex}/mobility-flow.svg`);
    });
  });
}
function bind(){document.querySelectorAll('[data-route]').forEach(x=>x.addEventListener('click',()=>go(x.dataset.route)));document.querySelectorAll('[data-exercise]').forEach(x=>x.addEventListener('click',()=>{state.selectedExercise=x.dataset.exercise;state.selectedSession=null;state.route='detail';save();render()}));document.querySelectorAll('[data-session]').forEach(x=>x.addEventListener('click',()=>{state.selectedSession=x.dataset.session;save();render()}));const drawer=document.getElementById('drawer'),overlay=document.getElementById('overlay');const menu=open=>{drawer?.classList.toggle('open',open);if(overlay)overlay.hidden=!open;document.body.classList.toggle('locked',open)};document.getElementById('openMenu')?.addEventListener('click',()=>menu(true));document.getElementById('closeMenu')?.addEventListener('click',()=>menu(false));overlay?.addEventListener('click',()=>menu(false));document.getElementById('generatePlan')?.addEventListener('click',()=>{if(!profileReady()){go('profile');return}state.plan=PLANNER.makePlan(state.profile,state.stats);state.calendarCursor=state.plan.sessions[0]?.date.slice(0,7)||null;save();toast('Plan personalizado generado');go('calendar')});document.getElementById('saveProfile')?.addEventListener('click',saveProfile);document.getElementById('resetAll')?.addEventListener('click',()=>{if(confirm('¿Borrar perfil, calendario y progreso?')){localStorage.removeItem(KEY);location.reload()}});document.getElementById('prevMonth')?.addEventListener('click',()=>moveMonth(-1));document.getElementById('nextMonth')?.addEventListener('click',()=>moveMonth(1));document.getElementById('closeModal')?.addEventListener('click',closeModal);document.getElementById('sessionModal')?.addEventListener('click',e=>{if(e.target.id==='sessionModal')closeModal()});document.getElementById('completeSession')?.addEventListener('click',e=>completeSession(e.currentTarget.dataset.id));document.getElementById('timerBtn')?.addEventListener('click',toggleTimer);document.getElementById('resetTimer')?.addEventListener('click',resetTimer)}
function moveMonth(delta){let d=state.calendarCursor?new Date(state.calendarCursor+'-01T12:00:00'):new Date();d.setMonth(d.getMonth()+delta);state.calendarCursor=monthKey(d);save();render()}
function closeModal(){state.selectedSession=null;save();render()}
function saveProfile(){const val=id=>document.getElementById(id)?.value;const p={...state.profile,name:val('name').trim(),sex:val('sex'),age:Number(val('age')),weight:Number(val('weight')),height:Number(val('height')),activity:val('activity'),goal:val('goal'),minutesPerSession:Number(val('minutes')),weekdays:[...document.querySelectorAll('[name=weekdays]:checked')].map(x=>Number(x.value)),equipment:[...document.querySelectorAll('[name=equipment]:checked')].map(x=>x.value),limitations:[...document.querySelectorAll('[name=limitations]:checked')].map(x=>x.value)};if(!p.name||!['male','female'].includes(p.sex)||p.age<16||p.age>90||p.weight<35||p.weight>250||p.height<130||p.height>220||!p.activity||!p.goal||p.minutesPerSession<7||p.minutesPerSession>90||!p.weekdays.length){toast('Revisa los campos y selecciona al menos un día');return}if(!p.equipment.length)p.equipment=['none'];if(!p.limitations.length)p.limitations=['none'];state.profile=p;state.plan=PLANNER.makePlan(p,state.stats);state.calendarCursor=state.plan.sessions[0]?.date.slice(0,7)||null;save();toast('Perfil y calendario actualizados');render()}
function completeSession(id){const s=state.plan?.sessions?.find(x=>x.id===id);if(!s||s.completed)return;s.completed=true;state.stats.workouts++;state.stats.xp+=100;state.stats.streak++;state.stats.bestStreak=Math.max(state.stats.bestStreak,state.stats.streak);state.stats.totalMinutes+=s.minutes;state.selectedSession=null;save();toast('Sesión completada · +100 XP');render()}
function timerViewUpdate(){const display=document.getElementById('timer');if(display)display.textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;const idx=Math.min(DATA.seven.length-1,Math.floor((420-remaining)/60)),item=DATA.seven[idx],ex=exById(item.exercise);const h=document.getElementById('activeExercise'),p=document.getElementById('activeSteps'),im=document.getElementById('activeImage');if(h)h.textContent=`Minuto ${idx+1}: ${ex.name}`;if(p)p.textContent=ex.steps.join(' ');if(im){im.src=imageFile(ex);im.alt=ex.name}}
function toggleTimer(){const btn=document.getElementById('timerBtn');if(timer){clearInterval(timer);timer=null;if(btn)btn.textContent='Reanudar';return}if(btn)btn.textContent='Pausar';timer=setInterval(()=>{remaining--;timerViewUpdate();if(remaining<=0){clearInterval(timer);timer=null;remaining=420;state.stats.workouts++;state.stats.xp+=100;state.stats.totalMinutes+=7;state.stats.streak++;state.stats.bestStreak=Math.max(state.stats.bestStreak,state.stats.streak);save();toast('7 Minute Workout completado · +100 XP');render()}},1000)}
function resetTimer(){if(timer)clearInterval(timer);timer=null;remaining=420;render()}
function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),2200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();
})();
