(() => {
'use strict';
const DATA=window.NEO_DATA, PLANNER=window.NEO_PLANNER, root=document.getElementById('app');
const KEY='neoTrainerV400';
const defaults={route:'home',profile:{name:'',sex:'male',age:null,weight:null,height:null,activity:'',goal:'',daysPerWeek:3,minutesPerSession:30,equipment:['none'],limitations:['none']},stats:{xp:0,workouts:0,streak:0,bestStreak:0,totalMinutes:0},plan:null};
function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x&&typeof x==='object'?x:null}catch{return null}}
const old=read();const cleanDefaults=JSON.parse(JSON.stringify(defaults));const state={...cleanDefaults,...(old||{})};state.profile={...defaults.profile,...(old?.profile||{})};state.stats={...defaults.stats,...(old?.stats||{})};
['xp','workouts','streak','bestStreak','totalMinutes'].forEach(k=>state.stats[k]=Math.max(0,Number(state.stats[k])||0));
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function img(id,phase=''){const sex=state.profile.sex==='female'?'female':'male';const file=phase?`${id}-${phase}.jpg`:(id==='pushup'?'pushup-start.jpg':`${id}.jpg`);return `assets/exercises/${sex}/${file}`}
function avatar(){return `assets/exercises/${state.profile.sex==='female'?'female':'male'}/avatar.jpg`}
function bmi(){return PLANNER.bmi(state.profile)}
function plan(){return state.plan?.ready?state.plan:PLANNER.makePlan(state.profile,state.stats)}
function level(){const x=state.stats.xp;return x>=5000?'Elite':x>=2500?'Avanzado':x>=1000?'Intermedio':x>=250?'Principiante':'Inicial'}
const nav=[['home','⌂','Inicio'],['calendar','▣','Calendario'],['workouts','✦','Entrenamientos'],['exercises','⚕','Ejercicios'],['progress','▥','Progreso'],['seven','◴','7 Min Workout'],['profile','●','Perfil']];
function go(route){state.route=route;save();render();scrollTo(0,0)}
function navHtml(cls='nav'){return `<nav class="${cls}">${nav.map(([r,i,l])=>`<button data-route="${r}" class="${state.route===r?'active':''}"><span>${i}</span>${l}</button>`).join('')}</nav>`}
function shell(content){return `<aside class="sidebar"><div class="brand"><b>NEO</b><span>TRAINER</span></div><section class="profile-card"><img src="${avatar()}" alt="Perfil"><h3>¡Hola, ${esc(state.profile.name||'Usuario')}!</h3><p>${level()}</p><strong>★ ${state.stats.xp} XP</strong><div><span>🔥 ${state.stats.streak} días</span><span>${state.stats.workouts} entrenos</span></div></section>${navHtml()}<footer>v${DATA.version} · ${DATA.build}<br>Creada por <a href="https://nachuss.github.io/" target="_blank" rel="noopener">@NachusS ↗</a></footer></aside><main class="main">${content}</main><div id="overlay" class="overlay" hidden></div><aside id="drawer" class="drawer" aria-hidden="true"><header><b>NEO Trainer</b><button id="closeMenu">✕</button></header><div class="drawer-user"><img src="${avatar()}" alt="Perfil"><div><b>${esc(state.profile.name||'Usuario')}</b><small>${level()} · ${state.stats.xp} XP</small></div></div>${navHtml('drawer-nav')}<footer>Creada por <a href="https://nachuss.github.io/" target="_blank" rel="noopener">@NachusS ↗</a></footer></aside><nav class="bottom-nav">${[['home','⌂','Inicio'],['workouts','✦','Entrenos'],['exercises','⚕','Ejercicios'],['seven','◴','7 Min'],['profile','●','Perfil']].map(([r,i,l])=>`<button data-route="${r}" class="${state.route===r?'active':''}"><span>${i}</span><small>${l}</small></button>`).join('')}</nav>`}
function top(title){return `<header class="topbar"><button id="openMenu">☰</button><h1>${title}</h1><button data-route="profile" class="avatar-btn"><img src="${avatar()}" alt="Perfil"></button></header>`}
function metric(label,value,sub=''){return `<div class="panel metric"><small>${label}</small><b>${value}</b><span>${sub}</span></div>`}
function home(){const b=bmi(),bi=PLANNER.bmiLabel(b),p=plan();return shell(`${top('Inicio')}<section class="metrics">${metric('XP total',state.stats.xp,'Puntos reales')}${metric('Entrenamientos',state.stats.workouts,'Completados')}${metric('Racha actual',`${state.stats.streak} días`,'Uso consecutivo')}${metric('IMC',b?b.toFixed(1):'—',bi.label)}</section><div class="home-grid"><section class="panel profile-summary"><img src="${avatar()}" alt="Perfil"><div><h2>${esc(state.profile.name||'Completa tu perfil')}</h2><dl><div><dt>Sexo</dt><dd>${state.profile.sex==='female'?'Mujer':'Hombre'}</dd></div><div><dt>Edad</dt><dd>${state.profile.age?`${state.profile.age} años`:'—'}</dd></div><div><dt>Peso</dt><dd>${state.profile.weight?`${state.profile.weight} kg`:'—'}</dd></div><div><dt>Altura</dt><dd>${state.profile.height?`${state.profile.height} cm`:'—'}</dd></div><div><dt>IMC</dt><dd>${b?`${b.toFixed(1)} · ${bi.label}`:'—'}</dd></div></dl><button class="btn primary" data-route="profile">Ver / editar perfil</button></div></section><section class="panel recommendation"><div><span class="tag">PLAN PERSONALIZADO</span><h2>${p.ready?'Tu entrenamiento recomendado':'Falta completar el perfil'}</h2><p>${p.ready?p.reason:p.reason}</p>${p.ready?`<ul><li>${p.days} días por semana</li><li>Intensidad ${p.intensity.label.toLowerCase()}</li><li>${p.intensity.sets} series · ${p.intensity.rest}s de descanso</li><li>${p.exercises.length} ejercicios adaptados</li></ul>`:''}<button class="btn primary" id="generatePlan">${p.ready?'Generar mi calendario':'Completar perfil'}</button></div><img src="${img(p.exercises?.[0]?.id||'incline')}" alt="Ejercicio recomendado"></section></div><section class="section-head"><h2>Biblioteca de ejercicios</h2><button data-route="exercises">Ver todos</button></section>${exerciseCards(DATA.exercises)}`)}
function exerciseCards(list){return `<section class="exercise-grid">${list.map(x=>`<article class="exercise-card panel" data-exercise="${x.id}"><img src="${img(x.id)}" alt="${esc(x.name)}"><div><small>${x.area}</small><h3>${x.name}</h3><span>Nivel ${x.level} · ${x.reps}</span></div></article>`).join('')}</section>`}
function exercises(){const recommended=PLANNER.selectExercises(state.profile,state.stats).map(x=>x.id);return shell(`${top('Ejercicios')}<section class="panel intro"><h2>Biblioteca adaptativa</h2><p>Las imágenes cambian automáticamente según el sexo del perfil. Los ejercicios marcados como recomendados se filtran por edad, IMC, actividad, limitaciones, material y progreso.</p></section>${exerciseCards(DATA.exercises.map(x=>({...x,recommended:recommended.includes(x.id)})))}`)}
function detail(id='pushup'){const ex=DATA.exercises.find(x=>x.id===id)||DATA.exercises[2];return shell(`${top(ex.name)}<div class="detail-layout"><div><section class="panel hero-poses"><div><h3>POSICIÓN INICIAL</h3><img src="${img(ex.id,ex.id==='pushup'?'start':'')}" alt="Posición inicial"></div><div><h3>POSICIÓN FINAL</h3><img src="${img(ex.id,ex.id==='pushup'?'end':'')}" alt="Posición final"></div></section><div class="info-grid"><section class="panel"><h3>DESCRIPCIÓN</h3><ol>${ex.steps.map(s=>`<li>${s}</li>`).join('')}</ol></section><section class="panel"><h3>MÚSCULOS PRINCIPALES</h3><img class="anatomy" src="assets/exercises/anatomy.jpg" alt="Músculos"><p>${ex.muscles}</p></section><section class="panel stats"><div><small>Nivel</small><b>${ex.level}</b></div><div><small>Repeticiones</small><b>${ex.reps}</b></div><div><small>Impacto</small><b>${ex.impact}</b></div><div><small>Material</small><b>${ex.equipment.join(', ')}</b></div></section></div></div><aside><section class="panel"><h3>ADAPTACIÓN DEL PERFIL</h3><p>${PLANNER.readiness(state.profile)?`Este ejercicio se evalúa con tu edad (${state.profile.age}), IMC (${bmi().toFixed(1)}), actividad y limitaciones.`:'Completa tu perfil para recibir una evaluación personalizada.'}</p></section><section class="panel"><h3>CONSEJOS</h3><ul><li>Detén la serie si pierdes la técnica.</li><li>Respira con normalidad.</li><li>No entrenes con dolor agudo.</li></ul></section></aside></div>`)}
function workouts(){const p=plan();return shell(`${top('Entrenamientos')}${!p.ready?`<section class="panel empty"><h2>Completa tu perfil</h2><p>${p.reason}</p><button class="btn primary" data-route="profile">Ir al perfil</button></section>`:`<section class="panel plan-card"><div><span class="tag">PLAN DE 4 SEMANAS</span><h2>${p.days} días por semana · ${p.intensity.label}</h2><p>${p.reason}</p></div><div class="plan-stats"><b>${p.sessions.length}<small>sesiones</small></b><b>${state.profile.minutesPerSession}<small>min/sesión</small></b><b>${p.intensity.sets}<small>series</small></b></div><button id="generatePlan" class="btn primary">Regenerar calendario</button></section>${exerciseCards(p.exercises)}<section class="panel complete-box"><button id="completeWorkout" class="btn success">Completar sesión de hoy</button></section>`}`)}
function calendar(){const p=state.plan?.ready?state.plan:plan(),now=new Date(),y=now.getFullYear(),m=now.getMonth(),first=(new Date(y,m,1).getDay()+6)%7,total=new Date(y,m+1,0).getDate(),sessions=new Map((p.sessions||[]).map(s=>[s.date,s]));let cells='';for(let i=0;i<first;i++)cells+='<div></div>';for(let d=1;d<=total;d++){const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,s=sessions.get(iso);cells+=`<div class="calendar-day ${s?'scheduled':''} ${s?.completed?'done':''}"><b>${d}</b>${s?`<small>${s.completed?'Completado':'Entreno'}</small>`:''}</div>`}return shell(`${top('Calendario')}<section class="panel"><div class="section-head"><div><h2>${new Intl.DateTimeFormat('es-ES',{month:'long',year:'numeric'}).format(now)}</h2><p>${p.ready?'Calendario generado según tu perfil.':'Completa tu perfil para programar sesiones.'}</p></div><button id="generatePlan" class="btn primary">Generar plan</button></div><div class="week">${['L','M','X','J','V','S','D'].map(x=>`<b>${x}</b>`).join('')}</div><div class="calendar">${cells}</div></section>`)}
function progress(){const max=Math.max(1,state.stats.workouts),pct=Math.min(100,Math.round(max/20*100));return shell(`${top('Progreso')}<section class="metrics">${metric('Entrenamientos',state.stats.workouts)}${metric('XP',state.stats.xp)}${metric('Mejor racha',`${state.stats.bestStreak} días`)}${metric('Tiempo total',`${state.stats.totalMinutes} min`)}</section><section class="panel"><h2>Progreso real</h2><p>Todos los valores comenzaron en cero y solo aumentan al completar sesiones.</p><div class="progress"><span style="width:${pct}%"></span></div></section>`)}
function seven(){const ready=PLANNER.readiness(state.profile),risk=PLANNER.riskScore(state.profile),label=risk>=4?'Versión de bajo impacto':'Versión estándar';return shell(`${top('7 Minute Workout')}<section class="panel seven"><div><span class="tag">HIIT ADAPTADO</span><h2>${label}</h2><p>${ready?`Configurado para ${state.profile.age} años, IMC ${bmi().toFixed(1)} y actividad ${state.profile.activity}.`:'Completa primero el perfil para adaptar la sesión.'}</p><div id="timer">07:00</div><button id="timerBtn" class="btn primary" ${ready?'':'disabled'}>Iniciar</button></div><img src="${img(risk>=4?'incline':'pushup')}" alt="7 Minute Workout"></section>`)}
function profile(){const b=bmi(),bi=PLANNER.bmiLabel(b);return shell(`${top('Perfil')}<div class="profile-layout"><section class="panel"><h2>Datos personales y objetivos</h2><div class="form-grid"><label>Nombre<input id="name" value="${esc(state.profile.name)}"></label><label>Sexo<select id="sex"><option value="male" ${state.profile.sex==='male'?'selected':''}>Hombre</option><option value="female" ${state.profile.sex==='female'?'selected':''}>Mujer</option></select></label><label>Edad<input id="age" type="number" min="16" max="90" value="${state.profile.age??''}"></label><label>Peso (kg)<input id="weight" type="number" min="35" max="250" step="0.1" value="${state.profile.weight??''}"></label><label>Altura (cm)<input id="height" type="number" min="130" max="220" value="${state.profile.height??''}"></label><label>Actividad<select id="activity"><option value="">Selecciona</option>${DATA.activity.map(([v,l])=>`<option value="${v}" ${state.profile.activity===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Objetivo<select id="goal"><option value="">Selecciona</option>${DATA.goals.map(([v,l])=>`<option value="${v}" ${state.profile.goal===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Días por semana<input id="days" type="number" min="2" max="6" value="${state.profile.daysPerWeek}"></label><label>Minutos por sesión<input id="minutes" type="number" min="7" max="90" value="${state.profile.minutesPerSession}"></label></div><h3>Material disponible</h3><div class="checks">${DATA.equipment.map(([v,l])=>`<label><input type="checkbox" name="equipment" value="${v}" ${state.profile.equipment.includes(v)?'checked':''}>${l}</label>`).join('')}</div><h3>Limitaciones</h3><div class="checks">${DATA.limitations.map(([v,l])=>`<label><input type="checkbox" name="limitations" value="${v}" ${state.profile.limitations.includes(v)?'checked':''}>${l}</label>`).join('')}</div><div class="actions"><button id="saveProfile" class="btn primary">Guardar y recalcular</button><button id="resetAll" class="btn">Reiniciar aplicación</button></div><p class="note">El IMC y la planificación son orientativos. Ante enfermedad, embarazo, lesión importante o síntomas durante el ejercicio, consulta con un profesional sanitario.</p></section><aside class="panel bmi-card"><img src="${avatar()}" alt="Perfil"><small>Índice de masa corporal</small><b>${b?b.toFixed(1):'—'}</b><span class="status ${bi.tone}">${bi.label}</span><p>Se utiliza junto con edad, sexo, actividad, objetivos, material, limitaciones y progreso; nunca como único criterio.</p></aside></div>`)}
function render(){try{const views={home,calendar,workouts,exercises,progress,seven,profile};root.innerHTML=(state.route==='detail'?detail(state.selectedExercise):views[state.route]||home)();bind()}catch(e){console.error(e);root.innerHTML=`<div class="fatal-screen"><h1>Error al cargar</h1><pre>${esc(e.message)}</pre><button id="resetAll">Restablecer</button></div>`;document.getElementById('resetAll')?.addEventListener('click',()=>{localStorage.removeItem(KEY);location.reload()})}}
let timer=null,remaining=420;
function bind(){document.querySelectorAll('[data-route]').forEach(x=>x.addEventListener('click',()=>go(x.dataset.route)));document.querySelectorAll('[data-exercise]').forEach(x=>x.addEventListener('click',()=>{state.selectedExercise=x.dataset.exercise;state.route='detail';save();render()}));const drawer=document.getElementById('drawer'),overlay=document.getElementById('overlay');const menu=open=>{drawer?.classList.toggle('open',open);if(overlay)overlay.hidden=!open;document.body.classList.toggle('locked',open)};document.getElementById('openMenu')?.addEventListener('click',()=>menu(true));document.getElementById('closeMenu')?.addEventListener('click',()=>menu(false));overlay?.addEventListener('click',()=>menu(false));document.getElementById('generatePlan')?.addEventListener('click',()=>{if(!PLANNER.readiness(state.profile)){go('profile');return}state.plan=PLANNER.makePlan(state.profile,state.stats);save();toast('Plan personalizado generado');go('calendar')});document.getElementById('completeWorkout')?.addEventListener('click',completeWorkout);document.getElementById('saveProfile')?.addEventListener('click',saveProfile);document.getElementById('resetAll')?.addEventListener('click',()=>{if(confirm('¿Borrar perfil, calendario y progreso?')){localStorage.removeItem(KEY);location.reload()}});document.getElementById('timerBtn')?.addEventListener('click',toggleTimer)}
function saveProfile(){const val=id=>document.getElementById(id)?.value;const profile={...state.profile,name:val('name').trim(),sex:val('sex'),age:Number(val('age')),weight:Number(val('weight')),height:Number(val('height')),activity:val('activity'),goal:val('goal'),daysPerWeek:Number(val('days')),minutesPerSession:Number(val('minutes')),equipment:[...document.querySelectorAll('[name=equipment]:checked')].map(x=>x.value),limitations:[...document.querySelectorAll('[name=limitations]:checked')].map(x=>x.value)};if(!profile.name||!['male','female'].includes(profile.sex)||profile.age<16||profile.age>90||profile.weight<35||profile.weight>250||profile.height<130||profile.height>220||!profile.activity||!profile.goal||profile.daysPerWeek<2||profile.daysPerWeek>6||profile.minutesPerSession<7||profile.minutesPerSession>90){toast('Revisa todos los campos obligatorios');return}if(!profile.equipment.length)profile.equipment=['none'];if(!profile.limitations.length)profile.limitations=['none'];state.profile=profile;state.plan=PLANNER.makePlan(profile,state.stats);save();toast('Perfil guardado y plan recalculado');render()}
function completeWorkout(){state.stats.workouts++;state.stats.xp+=100;state.stats.streak++;state.stats.bestStreak=Math.max(state.stats.bestStreak,state.stats.streak);state.stats.totalMinutes+=Number(state.profile.minutesPerSession)||30;if(state.plan?.sessions){const today=new Date().toISOString().slice(0,10),s=state.plan.sessions.find(x=>x.date===today&&!x.completed)||state.plan.sessions.find(x=>!x.completed);if(s)s.completed=true}save();toast('Sesión completada · +100 XP');render()}
function toggleTimer(){const display=document.getElementById('timer'),btn=document.getElementById('timerBtn');if(timer){clearInterval(timer);timer=null;btn.textContent='Reanudar';return}btn.textContent='Pausar';timer=setInterval(()=>{remaining--;if(display)display.textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;if(remaining<=0){clearInterval(timer);timer=null;remaining=420;completeWorkout()}},1000)}
function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),2200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();
})();
