'use strict';
window.NEO_DATA = {
  version:'4.1.0', build:'28/07/2026 16:25',
  equipment:[['none','Sin material'],['mat','Esterilla'],['dumbbells','Mancuernas'],['bands','Bandas'],['pullup','Barra de dominadas'],['bench','Banco'],['trx','TRX'],['kettlebell','Kettlebell']],
  goals:[['general','Mejorar condición física'],['fatloss','Reducir grasa corporal'],['strength','Ganar fuerza'],['muscle','Ganar masa muscular'],['mobility','Mejorar movilidad'],['lower','Potenciar piernas'],['pullupGoal','Conseguir dominadas']],
  activity:[['sedentary','Sedentario'],['light','Actividad ligera'],['moderate','Actividad moderada'],['active','Muy activo']],
  limitations:[['none','Ninguna'],['knees','Rodillas'],['back','Espalda'],['shoulders','Hombros'],['wrists','Muñecas'],['cardio','Limitación cardiovascular']],
  weekdays:[['1','Lunes'],['2','Martes'],['3','Miércoles'],['4','Jueves'],['5','Viernes'],['6','Sábado'],['7','Domingo']],
  exercises:[
    {id:'incline',name:'Flexiones inclinadas',area:'Pecho',level:1,impact:'low',equipment:['none'],avoid:['wrists'],reps:'8–12',muscles:'Pecho, tríceps y hombros',image:'incline',youtube:'flexiones inclinadas técnica',steps:['Apoya las manos en una superficie estable.','Alinea cabeza, tronco y piernas.','Baja el pecho con control.','Empuja hasta recuperar la posición inicial.']},
    {id:'knees',name:'Flexiones con rodillas',area:'Pecho',level:1,impact:'low',equipment:['mat'],avoid:['knees','wrists'],reps:'8–12',muscles:'Pecho, tríceps y core',image:'knees',youtube:'flexiones con rodillas técnica',steps:['Apoya rodillas y manos.','Activa abdomen y glúteos.','Baja el pecho manteniendo espalda neutra.','Regresa de forma controlada.']},
    {id:'pushup',name:'Flexiones de pecho',area:'Pecho',level:2,impact:'medium',equipment:['none'],avoid:['wrists','shoulders'],reps:'6–12',muscles:'Pecho, tríceps, hombros y core',image:'pushup',youtube:'flexiones de pecho técnica correcta',steps:['Coloca las manos algo más anchas que los hombros.','Mantén el cuerpo en línea recta.','Flexiona los codos y baja el pecho.','Empuja hasta volver al inicio.']},
    {id:'squat',name:'Sentadillas',area:'Piernas',level:1,impact:'low',equipment:['none'],avoid:['knees'],reps:'10–15',muscles:'Cuádriceps, glúteos y core',image:'incline',youtube:'sentadilla técnica correcta',steps:['Separa los pies al ancho de los hombros.','Lleva la cadera atrás y flexiona rodillas.','Mantén el pecho elevado.','Empuja el suelo para subir.']},
    {id:'reverse-lunge',name:'Zancadas hacia atrás',area:'Piernas',level:2,impact:'low',equipment:['none'],avoid:['knees'],reps:'8–12 por lado',muscles:'Glúteos, cuádriceps e isquiotibiales',image:'knees',youtube:'zancada hacia atrás técnica',steps:['Da un paso atrás amplio.','Desciende ambas rodillas con control.','Mantén el tronco erguido.','Regresa empujando con el pie delantero.']},
    {id:'glute-bridge',name:'Puente de glúteos',area:'Glúteos',level:1,impact:'low',equipment:['mat'],avoid:[],reps:'12–20',muscles:'Glúteos, isquiotibiales y core',image:'decline',youtube:'puente de glúteos técnica',steps:['Túmbate con rodillas flexionadas.','Apoya los pies cerca de los glúteos.','Eleva la cadera apretando glúteos.','Baja sin perder el control.']},
    {id:'calf-raise',name:'Elevaciones de gemelos',area:'Piernas',level:1,impact:'low',equipment:['none'],avoid:[],reps:'15–25',muscles:'Gemelos y sóleo',image:'incline',youtube:'elevaciones de gemelos técnica',steps:['Colócate erguido.','Eleva los talones.','Mantén un segundo arriba.','Baja lentamente.']},
    {id:'wall-sit',name:'Sentadilla en pared',area:'Piernas',level:1,impact:'low',equipment:['none'],avoid:['knees'],reps:'20–45 s',muscles:'Cuádriceps y glúteos',image:'decline',youtube:'sentadilla isométrica pared técnica',steps:['Apoya la espalda en la pared.','Deslízate hasta una posición cómoda.','Mantén rodillas alineadas.','Respira y conserva la tensión.']},
    {id:'plank',name:'Plancha frontal',area:'Core',level:1,impact:'low',equipment:['mat'],avoid:['shoulders'],reps:'20–45 s',muscles:'Abdominales, glúteos y hombros',image:'pushup',youtube:'plancha frontal técnica correcta',steps:['Apoya antebrazos y puntas de los pies.','Alinea el cuerpo.','Aprieta abdomen y glúteos.','Evita hundir la zona lumbar.']},
    {id:'dead-bug',name:'Dead bug',area:'Core',level:1,impact:'low',equipment:['mat'],avoid:[],reps:'8–12 por lado',muscles:'Core profundo y flexores de cadera',image:'knees',youtube:'dead bug ejercicio técnica',steps:['Túmbate boca arriba con brazos elevados.','Coloca caderas y rodillas a 90 grados.','Extiende brazo y pierna contrarios.','Vuelve y alterna sin arquear la espalda.']},
    {id:'bird-dog',name:'Bird dog',area:'Core',level:1,impact:'low',equipment:['mat'],avoid:['wrists'],reps:'8–12 por lado',muscles:'Core, glúteos y espalda',image:'knees',youtube:'bird dog ejercicio técnica',steps:['Colócate a cuatro apoyos.','Extiende brazo y pierna contrarios.','Mantén la pelvis estable.','Regresa y cambia de lado.']},
    {id:'mountain-climber',name:'Escaladores',area:'Cardio · Core',level:2,impact:'medium',equipment:['mat'],avoid:['wrists','shoulders','cardio'],reps:'20–40 s',muscles:'Core, hombros y piernas',image:'pushup',youtube:'mountain climbers técnica',steps:['Adopta una plancha alta.','Lleva una rodilla hacia el pecho.','Alterna piernas sin elevar la cadera.','Mantén un ritmo controlado.']},
    {id:'superman',name:'Superman',area:'Espalda',level:1,impact:'low',equipment:['mat'],avoid:['back'],reps:'10–15',muscles:'Espalda, glúteos y hombros',image:'decline',youtube:'superman ejercicio espalda técnica',steps:['Túmbate boca abajo.','Extiende brazos y piernas.','Eleva suavemente extremidades.','Baja con control sin forzar el cuello.']},
    {id:'dumbbell-row',name:'Remo con mancuerna',area:'Espalda',level:2,impact:'low',equipment:['dumbbells'],avoid:['back'],reps:'8–12 por lado',muscles:'Dorsal, romboides y bíceps',image:'diamond',youtube:'remo con mancuerna técnica',steps:['Apoya una mano en una superficie estable.','Mantén la espalda neutra.','Lleva la mancuerna hacia la cadera.','Baja lentamente.']},
    {id:'band-row',name:'Remo con banda',area:'Espalda',level:1,impact:'low',equipment:['bands'],avoid:[],reps:'12–15',muscles:'Dorsal, romboides y bíceps',image:'diamond',youtube:'remo con banda elástica técnica',steps:['Fija la banda de forma segura.','Tira llevando los codos atrás.','Junta suavemente las escápulas.','Regresa sin perder tensión.']},
    {id:'shoulder-press',name:'Press de hombros',area:'Hombros',level:2,impact:'low',equipment:['dumbbells'],avoid:['shoulders'],reps:'8–12',muscles:'Deltoides y tríceps',image:'explosive',youtube:'press hombros mancuernas técnica',steps:['Sujeta las mancuernas a la altura de hombros.','Activa el core.','Empuja hacia arriba sin arquear la espalda.','Baja con control.']},
    {id:'lateral-raise',name:'Elevaciones laterales',area:'Hombros',level:2,impact:'low',equipment:['dumbbells'],avoid:['shoulders'],reps:'10–15',muscles:'Deltoides lateral',image:'explosive',youtube:'elevaciones laterales técnica',steps:['Mantén los brazos ligeramente flexionados.','Eleva hasta la altura de hombros.','Evita encoger el cuello.','Baja lentamente.']},
    {id:'biceps-curl',name:'Curl de bíceps',area:'Brazos',level:1,impact:'low',equipment:['dumbbells'],avoid:[],reps:'10–15',muscles:'Bíceps y antebrazos',image:'diamond',youtube:'curl bíceps mancuernas técnica',steps:['Mantén codos pegados al cuerpo.','Flexiona los brazos sin balancearte.','Aprieta arriba.','Baja completamente con control.']},
    {id:'chair-dip',name:'Fondos en silla',area:'Tríceps',level:2,impact:'medium',equipment:['bench'],avoid:['shoulders','wrists'],reps:'6–12',muscles:'Tríceps, pecho y hombros',image:'decline',youtube:'fondos en silla técnica',steps:['Apoya las manos en una silla estable.','Mantén la cadera cerca del borde.','Flexiona codos hacia atrás.','Empuja sin bloquear bruscamente.']},
    {id:'step-up',name:'Subidas a escalón',area:'Piernas · Cardio',level:2,impact:'medium',equipment:['bench'],avoid:['knees','cardio'],reps:'8–12 por lado',muscles:'Glúteos y cuádriceps',image:'incline',youtube:'step up ejercicio técnica',steps:['Apoya todo el pie en el escalón.','Sube empujando con la pierna superior.','Controla la rodilla.','Baja lentamente y alterna.']},
    {id:'jumping-jack',name:'Jumping jacks',area:'Cardio',level:2,impact:'high',equipment:['none'],avoid:['knees','cardio'],reps:'30–60 s',muscles:'Cuerpo completo',image:'explosive',youtube:'jumping jacks técnica',steps:['Comienza con pies juntos.','Salta abriendo piernas y elevando brazos.','Aterriza suavemente.','Mantén un ritmo adecuado.']},
    {id:'march',name:'Marcha activa',area:'Cardio',level:1,impact:'low',equipment:['none'],avoid:[],reps:'45–60 s',muscles:'Piernas y core',image:'incline',youtube:'marcha en el sitio ejercicio',steps:['Camina en el sitio.','Eleva las rodillas a una altura cómoda.','Mueve los brazos.','Mantén postura erguida.']},
    {id:'burpee-low',name:'Burpee sin salto',area:'Full body',level:2,impact:'medium',equipment:['mat'],avoid:['wrists','shoulders','cardio'],reps:'6–10',muscles:'Piernas, core, pecho y hombros',image:'pushup',youtube:'burpee sin salto técnica',steps:['Agáchate y apoya las manos.','Lleva los pies atrás uno a uno.','Vuelve hacia las manos.','Ponte de pie sin salto.']},
    {id:'mobility-flow',name:'Movilidad de cuerpo completo',area:'Movilidad',level:1,impact:'low',equipment:['mat'],avoid:[],reps:'5–8 min',muscles:'Caderas, columna y hombros',image:'knees',youtube:'rutina movilidad cuerpo completo principiantes',steps:['Realiza movimientos lentos y amplios.','Respira de forma continua.','No fuerces rangos dolorosos.','Mantén cada transición controlada.']}
  ],
  seven:[
    {exercise:'march',seconds:60},{exercise:'squat',seconds:60},{exercise:'incline',seconds:60},{exercise:'reverse-lunge',seconds:60},{exercise:'plank',seconds:60},{exercise:'glute-bridge',seconds:60},{exercise:'mountain-climber',seconds:60}
  ],
  sevenVideos:[
    {name:'7 Minute Workout — búsqueda en YouTube',query:'7 minute workout full body no equipment'},
    {name:'Scientific 7-Minute Workout — búsqueda',query:'scientific 7 minute workout official'},
    {name:'7 Minute Workout para principiantes',query:'7 minute workout beginners low impact'}
  ]
};
