'use strict';
window.NEO_PLANNER=(()=>{
 const D=()=>window.NEO_DATA;
 function bmi(p){const w=Number(p.weight),h=Number(p.height)/100;return w>0&&h>0?w/(h*h):null}
 function bmiLabel(v){if(v===null)return{label:'Pendiente',tone:'neutral'};if(v<18.5)return{label:'Peso bajo',tone:'amber'};if(v<25)return{label:'Rango saludable',tone:'green'};if(v<30)return{label:'Sobrepeso',tone:'amber'};if(v<35)return{label:'Obesidad grado I',tone:'red'};if(v<40)return{label:'Obesidad grado II',tone:'red'};return{label:'Obesidad grado III',tone:'red'}}
 function readiness(p){return ['name','sex','age','weight','height','activity','goal','minutesPerSession'].every(k=>p[k]!==null&&p[k]!==''&&p[k]!==undefined)&&Array.isArray(p.weekdays)&&p.weekdays.length>0}
 function riskScore(p){const age=+p.age||30,b=bmi(p),l=p.limitations||[];let s=0;if(age>=65)s+=3;else if(age>=55)s+=2;else if(age>=45)s++;if(b!==null){if(b>=35||b<17)s+=3;else if(b>=30||b<18.5)s+=2;else if(b>=27)s++}if(p.activity==='sedentary')s+=2;if(l.includes('cardio'))s+=3;s+=Math.min(2,l.filter(x=>x!=='none').length);return s}
 function intensity(p,stats){const r=riskScore(p),w=+stats.workouts||0;if(r>=6)return{level:1,label:'Muy suave',sets:2,rest:105};if(r>=4)return{level:1,label:'Suave',sets:2,rest:90};if(r>=2)return{level:2,label:'Moderada',sets:3,rest:75};if(w>=12&&p.activity==='active')return{level:4,label:'Alta',sets:4,rest:45};if(w>=5)return{level:3,label:'Media-alta',sets:3,rest:60};return{level:2,label:'Moderada',sets:3,rest:75}}
 function available(ex,p,lvl){const eq=p.equipment||['none'],limits=p.limitations||[];return (ex.equipment.includes('none')||ex.equipment.some(x=>eq.includes(x)))&&!ex.avoid.some(x=>limits.includes(x))&&ex.level<=Math.max(1,lvl)}
 function selectExercises(p,stats){const i=intensity(p,stats);let list=D().exercises.filter(x=>available(x,p,i.level));if(!list.length)list=D().exercises.filter(x=>['march','mobility-flow','incline'].includes(x.id));const priority={lower:['Piernas','Glúteos'],pullupGoal:['Espalda','Core'],strength:['Espalda','Piernas','Pecho'],muscle:['Pecho','Espalda','Piernas'],mobility:['Movilidad','Core'],fatloss:['Cardio','Full body'],general:['Core','Piernas','Pecho']};const areas=priority[p.goal]||priority.general;list.sort((a,b)=>{const ai=areas.findIndex(x=>a.area.includes(x)),bi=areas.findIndex(x=>b.area.includes(x));return (ai<0?99:ai)-(bi<0?99:bi)||a.level-b.level});return list.slice(0,Math.min(14,list.length))}
 function makePlan(p,stats,startDate=new Date()){if(!readiness(p))return{ready:false,reason:'Completa el perfil y selecciona los días de entrenamiento.'};const i=intensity(p,stats),chosen=selectExercises(p,stats),weekdays=[...new Set(p.weekdays.map(Number))].filter(x=>x>=1&&x<=7).sort(),sessions=[];const start=new Date(startDate);start.setHours(12,0,0,0);for(let offset=0;offset<35;offset++){const d=new Date(start);d.setDate(start.getDate()+offset);const wd=d.getDay()===0?7:d.getDay();if(!weekdays.includes(wd))continue;const index=sessions.length;const groups=[chosen.filter(x=>/(Piernas|Glúteos)/.test(x.area)),chosen.filter(x=>/(Pecho|Espalda|Hombros|Brazos|Tríceps)/.test(x.area)),chosen.filter(x=>/(Core|Cardio|Full body|Movilidad)/.test(x.area))];let pool=[...groups[index%3],...chosen].filter((x,j,a)=>a.findIndex(y=>y.id===x.id)===j);const count=Math.max(4,Math.min(7,Math.floor((+p.minutesPerSession||30)/6)));const exs=pool.slice(0,count).map(x=>x.id);sessions.push({id:`session-${d.toISOString().slice(0,10)}`,date:d.toISOString().slice(0,10),title:index%3===0?'Piernas y core':index%3===1?'Tren superior':'Full body y movilidad',minutes:+p.minutesPerSession||30,intensity:i.label,sets:i.sets,rest:i.rest,exercises:exs,completed:false})}
 return{ready:true,days:weekdays.length,weekdays,intensity:i,exercises:chosen,sessions,reason:`Plan de 4 semanas ajustado a edad, sexo, IMC, actividad, objetivo, material y limitaciones.`}}
 return{bmi,bmiLabel,readiness,riskScore,intensity,selectExercises,makePlan}
})();
