window.NEO_DATA = {
  version: "2.0",
  updated: "28/07/2026 10:58",
  publicUrl: "https://nachuss.github.io/NeoTrainer/",
  equipment: [
    ["none","Sin material","🧍"],["mat","Esterilla","▭"],["dumbbells","Mancuernas","🏋️"],
    ["bands","Bandas elásticas","➰"],["bar","Barra de dominadas","━"],["bench","Banco o cajón","▰"],
    ["kettlebell","Kettlebell","●"],["trx","TRX","⌁"],["backpack","Mochila","🎒"]
  ],
  goals: [
    ["fullbody","Full body","Fuerza y condición general"],
    ["lower","Piernas y cuádriceps","Potenciar tren inferior"],
    ["pullup","Progresión dominadas","Espalda, agarre y core"],
    ["definition","Definición","Circuitos de fuerza y cardio"],
    ["seven","7 Minute Workout","Circuito intensivo de 7 minutos"]
  ],
  exercises: [
    {id:"pushup",name:"Flexiones",category:"Pecho",level:"Básico",equipment:["none","mat"],home:"Rodillas apoyadas o manos sobre mesa estable",sets:"3",reps:"8–15",rest:"60 s",youtube:"https://www.youtube.com/results?search_query=push+up+proper+form",muscles:["Pecho","Tríceps","Hombro"],steps:["Manos algo más anchas que los hombros.","Cuerpo alineado y abdomen activo.","Baja el pecho controlando los codos.","Empuja el suelo hasta extender los brazos."],mistake:"Arquear la zona lumbar o abrir demasiado los codos.",motion:"pushup"},
    {id:"squat",name:"Sentadilla",category:"Piernas",level:"Básico",equipment:["none"],home:"Usa una silla como referencia de profundidad",sets:"4",reps:"12–20",rest:"60 s",youtube:"https://www.youtube.com/results?search_query=bodyweight+squat+proper+form",muscles:["Cuádriceps","Glúteos","Core"],steps:["Pies al ancho de hombros.","Lleva la cadera atrás y flexiona rodillas.","Mantén pecho erguido y rodillas alineadas.","Empuja el suelo para subir."],mistake:"Juntar las rodillas o despegar los talones.",motion:"squat"},
    {id:"lunge",name:"Zancada atrás",category:"Piernas",level:"Básico",equipment:["none"],home:"Apóyate suavemente en una pared si necesitas equilibrio",sets:"3",reps:"10 por lado",rest:"45 s",youtube:"https://www.youtube.com/results?search_query=reverse+lunge+proper+form",muscles:["Cuádriceps","Glúteos","Femorales"],steps:["Da un paso largo hacia atrás.","Desciende ambas rodillas de forma controlada.","Mantén el tronco vertical.","Regresa empujando con la pierna delantera."],mistake:"Paso demasiado corto y rodilla delantera colapsada hacia dentro.",motion:"lunge"},
    {id:"bridge",name:"Puente de glúteos",category:"Glúteos",level:"Básico",equipment:["mat"],home:"Toalla doblada sobre una superficie firme",sets:"4",reps:"15–20",rest:"45 s",youtube:"https://www.youtube.com/results?search_query=glute+bridge+proper+form",muscles:["Glúteos","Femorales","Core"],steps:["Túmbate con rodillas flexionadas.","Aprieta abdomen y glúteos.","Eleva la cadera hasta alinear rodillas y hombros.","Baja sin perder el control."],mistake:"Hiperextender la espalda en lugar de contraer glúteos.",motion:"bridge"},
    {id:"plank",name:"Plancha frontal",category:"Core",level:"Básico",equipment:["mat"],home:"Toalla doblada bajo los antebrazos",sets:"3",reps:"25–45 s",rest:"45 s",youtube:"https://www.youtube.com/results?search_query=forearm+plank+proper+form",muscles:["Core","Hombros","Glúteos"],steps:["Antebrazos bajo los hombros.","Activa abdomen y glúteos.","Forma una línea recta de cabeza a talones.","Respira sin perder la posición."],mistake:"Cadera demasiado alta o hundida.",motion:"plank"},
    {id:"climber",name:"Mountain climbers",category:"Cardio",level:"Intermedio",equipment:["none","mat"],home:"Realízalos lentamente para reducir impacto",sets:"3",reps:"30 s",rest:"30 s",youtube:"https://www.youtube.com/results?search_query=mountain+climber+exercise+proper+form",muscles:["Core","Hombros","Flexores de cadera"],steps:["Comienza en plancha alta.","Lleva una rodilla hacia el pecho.","Alterna piernas manteniendo el tronco estable.","Aumenta el ritmo sin perder técnica."],mistake:"Rebotar la cadera y acortar demasiado el recorrido.",motion:"climber"},
    {id:"row",name:"Remo con mochila",category:"Espalda",level:"Básico",equipment:["backpack","dumbbells"],home:"Mochila con libros o garrafas",sets:"4",reps:"10–15",rest:"60 s",youtube:"https://www.youtube.com/results?search_query=bent+over+row+proper+form",muscles:["Dorsal","Romboides","Bíceps"],steps:["Inclina el tronco con espalda neutra.","Deja los brazos extendidos.","Lleva la carga hacia las costillas.","Desciende lentamente."],mistake:"Redondear la espalda o encoger los hombros.",motion:"row"},
    {id:"press",name:"Press de hombros",category:"Hombros",level:"Intermedio",equipment:["dumbbells","backpack"],home:"Botellas de agua o mochila ligera",sets:"3",reps:"8–12",rest:"60 s",youtube:"https://www.youtube.com/results?search_query=shoulder+press+proper+form",muscles:["Hombros","Tríceps","Core"],steps:["Carga a la altura de los hombros.","Aprieta abdomen y glúteos.","Empuja verticalmente sin arquear la espalda.","Baja de forma controlada."],mistake:"Compensar con la zona lumbar.",motion:"press"},
    {id:"bandpull",name:"Apertura con banda",category:"Espalda",level:"Básico",equipment:["bands"],home:"Sustituir por deslizamientos escapulares en pared",sets:"3",reps:"15–20",rest:"40 s",youtube:"https://www.youtube.com/results?search_query=band+pull+apart+proper+form",muscles:["Deltoides posterior","Romboides","Trapecio"],steps:["Sujeta la banda al frente.","Mantén brazos casi extendidos.","Separa las manos juntando escápulas.","Regresa lentamente."],mistake:"Elevar hombros o doblar demasiado los codos.",motion:"bandpull"},
    {id:"deadbug",name:"Dead bug",category:"Core",level:"Básico",equipment:["mat"],home:"Toalla o alfombra firme",sets:"3",reps:"8–12 por lado",rest:"45 s",youtube:"https://www.youtube.com/results?search_query=dead+bug+exercise+proper+form",muscles:["Core profundo","Flexores de cadera"],steps:["Túmbate con caderas y rodillas a 90°.","Pega la zona lumbar al suelo.","Extiende brazo y pierna contrarios.","Vuelve y alterna."],mistake:"Separar la zona lumbar del suelo.",motion:"deadbug"},
    {id:"jumpingjack",name:"Jumping jacks",category:"Cardio",level:"Básico",equipment:["none"],home:"Versión sin salto abriendo una pierna cada vez",sets:"1",reps:"30 s",rest:"10 s",youtube:"https://www.youtube.com/results?search_query=jumping+jacks+proper+form",muscles:["Piernas","Hombros","Cardio"],steps:["Comienza con pies juntos.","Salta abriendo piernas y elevando brazos.","Aterriza suavemente.","Vuelve a la posición inicial."],mistake:"Aterrizar con rigidez o perder alineación de rodillas.",motion:"jumpingjack"},
    {id:"stepup",name:"Step-up",category:"Piernas",level:"Básico",equipment:["bench"],home:"Primer peldaño firme y antideslizante",sets:"3",reps:"10 por lado",rest:"45 s",youtube:"https://www.youtube.com/results?search_query=step+up+exercise+proper+form",muscles:["Cuádriceps","Glúteos","Gemelos"],steps:["Coloca un pie completo sobre el escalón.","Impúlsate con la pierna elevada.","Extiende cadera y rodilla.","Baja lentamente."],mistake:"Impulsarse demasiado con la pierna del suelo.",motion:"stepup"}
  ]
};
